version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - type: tmpfs
        target: /app/output
    environment:
      - PYTHONPATH=/app
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - CLASSPATH=/app/synthea-with-dependencies.jar:/app/slf4j-api.jar:/app/slf4j-simple.jar
    command: uvicorn app.main:app --host 0.0.0.0 --reload
